language: node_js
node_js:
  - "9"
  - "10"
before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - node . --travis
deploy:
  - provider: npm
    api_key:
      secure: "bf48qX5RGW/k5Mo4V7Y86JgFY8/omSRu93LTR4Fnyzb+4K1FNUO4XjmSrJsuI7XPHjMX1lAh+V8UxdaOa8ERCPY8til72N9beetpXOXLdHkP4XfyWUVKns6mU0ntbPrQGllxWwilj/plizmlvOtJcGNK4o+bRt5EttRdFUpaExo7hUFrFTlxyC2V+KofymLwAEluTIWYTh3RwsurgNgaUGGNo2tjoDfXVAoDM7iiGpGn7kEQ2/5eV9+70d2sSNEDZ3KvKyW3tMWlxDpOPOg/3wO/k8AFq8tWiR2ZA5tci9/vlhFI5MsxRIePAnaXNlF9bDG4yzPLqjWWBZs9mXD1R0r6Be4hy+XpOtUsQsnVO7/bbjzNOUsNv07/5HPaTDdwcBzFtPUlkpjU3J40nAFYMqlfPI7uK0Ef3bjphk/ObipSggvJvdN8Se6aTuDJ+mtNq0UQu+m7uVVsxx2tQhGVV3gksC0z7H2rj0zA5fIoQkA1p+pBMICdjRRCssrmjAbjyd74FyN5M520uQC5nrn0uaH9Jm9VQxSf21vzvF7s2ivRiVL49E1IZ6OZL/+tj0/ouV9RjMN4dabiDPEP7/qmTOY6Pq1YcxDR8YYRP9UIEI530nHjPPenaSaKHNusR5qWgDwxz63Rd1Zyy8+Qclsmz1HSxVMMs33ew+yqQnmLtFE="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "bf48qX5RGW/k5Mo4V7Y86JgFY8/omSRu93LTR4Fnyzb+4K1FNUO4XjmSrJsuI7XPHjMX1lAh+V8UxdaOa8ERCPY8til72N9beetpXOXLdHkP4XfyWUVKns6mU0ntbPrQGllxWwilj/plizmlvOtJcGNK4o+bRt5EttRdFUpaExo7hUFrFTlxyC2V+KofymLwAEluTIWYTh3RwsurgNgaUGGNo2tjoDfXVAoDM7iiGpGn7kEQ2/5eV9+70d2sSNEDZ3KvKyW3tMWlxDpOPOg/3wO/k8AFq8tWiR2ZA5tci9/vlhFI5MsxRIePAnaXNlF9bDG4yzPLqjWWBZs9mXD1R0r6Be4hy+XpOtUsQsnVO7/bbjzNOUsNv07/5HPaTDdwcBzFtPUlkpjU3J40nAFYMqlfPI7uK0Ef3bjphk/ObipSggvJvdN8Se6aTuDJ+mtNq0UQu+m7uVVsxx2tQhGVV3gksC0z7H2rj0zA5fIoQkA1p+pBMICdjRRCssrmjAbjyd74FyN5M520uQC5nrn0uaH9Jm9VQxSf21vzvF7s2ivRiVL49E1IZ6OZL/+tj0/ouV9RjMN4dabiDPEP7/qmTOY6Pq1YcxDR8YYRP9UIEI530nHjPPenaSaKHNusR5qWgDwxz63Rd1Zyy8+Qclsmz1HSxVMMs33ew+yqQnmLtFE="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "TjHapCmUqsgyEMi63B8/hYf/GYknPODzA9MulKPEGMCMLqGduMFVdTGepGhqUBMqkXrgOgyP4jeZJzlPRkbBdoAZOrxSblrbIDftEuXgZSJxHeF+G9tTrtDy2w29gFRIJiFRiUOWvVVatWnOHRh5tSIO4Z6RS+PlJa4IslWJV3sLOXhNALFfvkHlkXGFSmqVYcOLBorA0lphyztT44SQxuXqKBx2Xqlq59V9fftPAS4PgSuZDs4v7cpgHxLBoOEI4RQIlyFR+075xQ7aJYt6EsbUV/bT3Vfz6qlyiU0v5nM3yrsWc1s9FUWe17v2VcpCdVPEsfNSUzbKmt4oBrL4uZERd3HhhwN4ZW26VxUTIcCBZ/fPsNTK7xsjYjTOZGmvY1e1OZAoHTJp81Hze6GpCy9Sj1+MB5mJWjp82ad7toE46TC+QhCqasjDesV37OLtQLU56FtMigb3AUjPDRp5BhEEjPDxBW2aMVyuiCRy15ByWG3XKl13FbYoHtyik4abRlCugvfnkoPIu2MEYkfE1yLDsm8qafNcQRN8sgRKbo521M9kjs7lm2OqcIwm22ueou5fcDt53a+PLFtwwZfdOpZplKykcAIoAuoal2BtvQuAaDPCDCW6BeJPuSN2iGeK3qhVY9FOWjdyRCD5gITDiV4JZGmQNurMd9Z0Wc3acmo="
    on:
      tags: true
    skip_cleanup: true
