language: node_js
node_js:
  - "9"
  - "10"
before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - node . --travis
deploy:
  - provider: npm
    api_key:
      secure: "V/z3xb9v67L2RZ0/+SUKfiG5JCchfwWet8dVZJNLVmZtUEwLLgpzpvYDv4HZSiv5VDPT+D+DWlKvWivyEU4lTKktnR55TwMw3CbGyI+6/zyvT571PeyVhe70z9fH01QM41D7Gq6z7z2S6X7kqofjJlb4kX4+k6uf2N1FGRF70bw36FFTy9RIsFAwZvRttGYYdjE98jOi17jBSvmWhO5Gt7iGXvNHgNhrql/kbvDLyEQ+7UyUqjVxLZ9GNce8xtLv8eTuERDHu1HniYk0QdgxhZ1yVGt9368yu7UY3KPyW3z8mdvBxVveCkFGGw9MOzPQF7K8QqS6vJqH3YbR+w5r1TkylmO7uhryUgWO2lonF6FWVXFpjzHVohkPbo7wO3dmIcI9I+nPKsJQyGNHiyynuFrVJVi629rXQqp+d8meiFf2zsqU/Tv4dbeDPx7iIyUL87zry2kgBVjrhp9N0MpNvCr0cjRpTRhLbkgODAlDoCXv+rram+R/ldA3E6hqGzbcm/g+cGThZmXMwh4Yyw0xV7fVg1ur8KKT/sjZy+eo66gqCnNf4L48mEf9Rve+4omsHqM0/VL0EQoiOU8pmKHj6dyTPucHARekn3a2rttgoIiMTeOqqjx/6VxZ1/dqAvaxsNaRdvzN8PdupuGM89IDYg2uGRxqj1Q2tOkCgZdq75I="
    email: "compulim@hotmail.com"
    on:
      branch: master
      node: "10"
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "V/z3xb9v67L2RZ0/+SUKfiG5JCchfwWet8dVZJNLVmZtUEwLLgpzpvYDv4HZSiv5VDPT+D+DWlKvWivyEU4lTKktnR55TwMw3CbGyI+6/zyvT571PeyVhe70z9fH01QM41D7Gq6z7z2S6X7kqofjJlb4kX4+k6uf2N1FGRF70bw36FFTy9RIsFAwZvRttGYYdjE98jOi17jBSvmWhO5Gt7iGXvNHgNhrql/kbvDLyEQ+7UyUqjVxLZ9GNce8xtLv8eTuERDHu1HniYk0QdgxhZ1yVGt9368yu7UY3KPyW3z8mdvBxVveCkFGGw9MOzPQF7K8QqS6vJqH3YbR+w5r1TkylmO7uhryUgWO2lonF6FWVXFpjzHVohkPbo7wO3dmIcI9I+nPKsJQyGNHiyynuFrVJVi629rXQqp+d8meiFf2zsqU/Tv4dbeDPx7iIyUL87zry2kgBVjrhp9N0MpNvCr0cjRpTRhLbkgODAlDoCXv+rram+R/ldA3E6hqGzbcm/g+cGThZmXMwh4Yyw0xV7fVg1ur8KKT/sjZy+eo66gqCnNf4L48mEf9Rve+4omsHqM0/VL0EQoiOU8pmKHj6dyTPucHARekn3a2rttgoIiMTeOqqjx/6VxZ1/dqAvaxsNaRdvzN8PdupuGM89IDYg2uGRxqj1Q2tOkCgZdq75I="
    email: "compulim@hotmail.com"
    on:
      tags: true
      node: "10"
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "TjHapCmUqsgyEMi63B8/hYf/GYknPODzA9MulKPEGMCMLqGduMFVdTGepGhqUBMqkXrgOgyP4jeZJzlPRkbBdoAZOrxSblrbIDftEuXgZSJxHeF+G9tTrtDy2w29gFRIJiFRiUOWvVVatWnOHRh5tSIO4Z6RS+PlJa4IslWJV3sLOXhNALFfvkHlkXGFSmqVYcOLBorA0lphyztT44SQxuXqKBx2Xqlq59V9fftPAS4PgSuZDs4v7cpgHxLBoOEI4RQIlyFR+075xQ7aJYt6EsbUV/bT3Vfz6qlyiU0v5nM3yrsWc1s9FUWe17v2VcpCdVPEsfNSUzbKmt4oBrL4uZERd3HhhwN4ZW26VxUTIcCBZ/fPsNTK7xsjYjTOZGmvY1e1OZAoHTJp81Hze6GpCy9Sj1+MB5mJWjp82ad7toE46TC+QhCqasjDesV37OLtQLU56FtMigb3AUjPDRp5BhEEjPDxBW2aMVyuiCRy15ByWG3XKl13FbYoHtyik4abRlCugvfnkoPIu2MEYkfE1yLDsm8qafNcQRN8sgRKbo521M9kjs7lm2OqcIwm22ueou5fcDt53a+PLFtwwZfdOpZplKykcAIoAuoal2BtvQuAaDPCDCW6BeJPuSN2iGeK3qhVY9FOWjdyRCD5gITDiV4JZGmQNurMd9Z0Wc3acmo="
    on:
      tags: true
    skip_cleanup: true
